In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [2]:
df_accident = pd.read_csv("C:/Users/USSB697670/Desktop/GeorgiaTech/Data Mining & Statistical Learning/Projects/Accident_Information.csv")

In [3]:
df_vehicle = pd.read_csv("C:/Users/USSB697670/Desktop/GeorgiaTech/Data Mining & Statistical Learning/Projects/Vehicle_Information.csv", encoding='unicode_escape')

In [4]:
df = pd.merge(df_accident, df_vehicle, on='Accident_Index')

In [5]:
df_f = df.iloc[:, [0,5,7,8,10,11,25,26,28,29,30,31,32,34,35,38,43,44,45,46]]

In [6]:
df_f

,Accident_Index,Accident_Severity,Date,Day_of_Week,Junction_Control,Junction_Detail,Road_Surface_Conditions,Road_Type,Speed_limit,Time,Urban_or_Rural_Area,Weather_Conditions,Year_x,Age_Band_of_Driver,Age_of_Vehicle,Engine_Capacity_.CC.,make,model,Propulsion_Code,Sex_of_Driver
0,200501BS00002,Slight,1/5/2005,Wednesday,Auto traffic signal,Crossroads,Dry,Dual carriageway,30,17:36,Urban,Fine no high winds,2005,36 - 45,3.0,8268.0,DENNIS,NaN,Heavy oil,Male
1,200501BS00003,Slight,1/6/2005,Thursday,Data missing or out of range,Not at junction or within 20 metres,Dry,Single carriageway,30,0:15,Urban,Fine no high winds,2005,26 - 35,5.0,8300.0,DENNIS,NaN,Heavy oil,Male
2,200501BS00004,Slight,1/7/2005,Friday,Data missing or out of range,Not at junction or within 20 metres,Dry,Single carriageway,30,10:35,Urban,Fine no high winds,2005,46 - 55,4.0,1769.0,NISSAN,ALMERA SE AUTO,Petrol,Female
3,200501BS00005,Slight,1/10/2005,Monday,Data missing or out of range,Not at junction or within 20 metres,Wet or damp,Single carriageway,30,21:13,Urban,Fine no high winds,2005,46 - 55,10.0,85.0,HONDA,NaN,Petrol,Male
4,200501BS00006,Slight,1/11/2005,Tuesday,Data missing or out of range,Not at junction or within 20 metres,Wet or damp,Single carriageway,30,12:40,Urban,Raining no high winds,2005,46 - 55,1.0,2976.0,AUDI,A4 SPORT CABRIOLET AUTO,Petrol,Male
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
528781,201091NM01935,Slight,2/23/2010,Tuesday,Give way or uncontrolled,T or staggered junction,Frost or ice,Single carriageway,30,9:38,Rural,Fine no high winds,2010,46 - 55,NaN,NaN,RENAULT,KANGOO ML19 PLUS 85 DCI,NaN,Male
528782,201091NM01935,Slight,2/23/2010,Tuesday,Give way or uncontrolled,T or staggered junction,Frost or ice,Single carriageway,30,9:38,Rural,Fine no high winds,2010,46 - 55,NaN,NaN,FORD,RANGER 4X4 TURBO DIESEL,NaN,Male
528783,201091NM01964,Serious,2/23/2010,Tuesday,Give way or uncontrolled,T or staggered junction,Wet or damp,Single carriageway,60,18:25,Rural,Fine no high winds,2010,36 - 45,11.0,955.0,TRIUMPH,SPRINT ST,Petrol,Male
528784,201091NM01964,Serious,2/23/2010,Tuesday,Give way or uncontrolled,T or staggered junction,Wet or damp,Single carriageway,60,18:25,Rural,Fine no high winds,2010,46 - 55,NaN,NaN,FORD,FIESTA 35,NaN,Male
528785,201091NM02142,Serious,2/28/2010,Sunday,Give way or uncontrolled,T or staggered junction,Wet or damp,Dual carriageway,60,15:45,Rural,Snowing no high winds,2010,26 - 35,13.0,1389.0,VAUXHALL,CORSA BREEZE HI-TORQ,Petrol,Female

# Exploratory Data Analysis

In [7]:
df_f.describe()

         Speed_limit         Year_x  Age_of_Vehicle  Engine_Capacity_.CC.
count  528786.000000  528786.000000   459227.000000         483509.000000
mean       39.312964    2007.789264        6.382345           2151.774726
std        14.294410       1.716493        4.468305           2123.511077
min        10.000000    2005.000000        1.000000              1.000000
25%        30.000000    2006.000000        3.000000           1299.000000
50%        30.000000    2008.000000        6.000000           1686.000000
75%        50.000000    2009.000000        9.000000           1998.000000
max        70.000000    2010.000000       85.000000          96000.000000

In [9]:
df_f.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 528786 entries, 0 to 528785
Data columns (total 20 columns):
 #   Column                   Non-Null Count   Dtype
---  ------                   --------------   -----
 0   Accident_Index           528786 non-null  object
 1   Accident_Severity        528786 non-null  object
 2   Date                     528786 non-null  object
 3   Day_of_Week              528786 non-null  object
 4   Junction_Control         528786 non-null  object
 5   Junction_Detail          528786 non-null  object
 6   Road_Surface_Conditions  528786 non-null  object
 7   Road_Type                528786 non-null  object
 8   Speed_limit              528786 non-null  int64
 9   Time                     528784 non-null  object
 10  Urban_or_Rural_Area      528786 non-null  object
 11  Weather_Conditions       528786 non-null  object
 12  Year_x                   528786 non-null  int64
 13  Age_Band_of_Driver       528786 non-null  object
 14  Age_of_Vehicle           459227 non-null  float64
 15  Engine_Capacity_.CC.     483509 non-null  float64
 16  make                     528786 non-null  object
 17  model                    453120 non-null  object
 18  Propulsion_Code          491485 non-null  object
 19  Sex_of_Driver            528786 non-null  object
dtypes: float64(2), int64(2), object(16)
memory usage: 80.7+ MB